1

5

In [2]:
string = tf.Variable("this is string", tf.string)
number = tf.Variable(324, tf.int16) #1 dimention
rank1_tensor = tf.Variable(['test', 'ok'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok', 'x'], ['ok2', 'kk', 'x']], tf.string)
tf.rank(rank2_tensor) #

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
rank2_tensor.shape

TensorShape([2, 3])

In [4]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [2,3,1])

In [5]:
tensor3 = tf.reshape(tensor1, [3,-1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [6]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [7]:
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [33]:
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib
import tensorflow.compat.v2.feature_column as fc
from sklearn.model_selection import train_test_split

In [34]:
# test = pd.read_csv("test.csv")
dftrain = pd.read_csv('train.csv') # training data
y_train = dftrain.pop('Survived')
X_train, X_test, y_train, y_test = train_test_split(dftrain, y_train, test_size=0.33, random_state=42)
# dfeval = pd.read_csv('test.csv') # testing data
# y_eval = dfeval.pop('Survived')

In [30]:
dfeval.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [31]:
dftrain.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [51]:
for column in dftrain.columns:
    try:
        if all([int(i) for i in dftrain[column].unique()]):
            print(column, "numeric")
    except:
        print(column, dftrain[column].unique()[0:10]) #     if dftrain[column].unique()


PassengerId numeric
Pclass numeric
Name ['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Nasser, Mrs. Nicholas (Adele Achem)']
Sex ['male' 'female']
Age [22. 38. 26. 35. nan 54.  2. 27. 14.  4.]
Ticket ['A/5 21171' 'PC 17599' 'STON/O2. 3101282' '113803' '373450' '330877'
 '17463' '349909' '347742' '237736']
Cabin [nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78']
Embarked ['S' 'C' 'Q' nan]


In [46]:
CATEGORICAL_COLUMNS = ['sex', 'n_siblings_spouses', 'parch', 'pclass', 'deck',
                       'embark_town', 'alone']
NUMERIC_COLUMNS = ['age', 'fare']

feature_columns = []
for feature_name in CATEGORICAL_COLUMNS:
  vocabulary = dftrain[feature_name].unique()  # gets a list of all unique values from given feature column
  feature_columns.append(tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary))

for feature_name in NUMERIC_COLUMNS:
  feature_columns.append(tf.feature_column.numeric_column(feature_name, dtype=tf.float32))

print(feature_columns)

True

In [ ]:
tf.data.Dataset.from_tensor_slices()

In [ ]:
linear_estimator = tf.estimator.LinearClassifier(feature_columns=feature_columns)
linear_estimator.train(train_input_fn)
result = linear_estimator.evaluate(eval_input_fn)
print(restult['accuracy'])

In [ ]:
7,7,7
10. 
1,1,1

In [61]:
intig = 21
intig%4

1

In [62]:
intig = 21
while intig %4!=0:
    print(intig)
    intig = intig-1


21


1 3 21
2 2 10
3 1 7
4 0 5


0

7
5


0

In [539]:
def return_last_position(position, blocks, reverse=False):
    last = blocks[position]
    j=0
    if reverse:
        blocks = blocks[::-1]
        for j, i in reversed(list(enumerate(blocks[position+1:]))):
            if i>= last:
                last = blocks[j]
                continue
            else:
                return position

    for j, i in enumerate(blocks[position+1:]):
        if i>= last:
            last = blocks[j]
            continue
        else:
            return position+j
    return position+j+1

In [548]:
possibilities = []

blocks = np.array([1,1])
# blocks = np.array([1,5,5,2,6])

for start_pos in range(0,len(blocks)):
    if start_pos==0:
        end_position = return_last_position(start_pos, blocks)
        print(start_pos, end_position)
        possibilities.append(end_position-start_pos+1)
    elif start_pos==(len(blocks)-1):
        end_position = return_last_position(start_pos, blocks, reverse=True)
        print(start_pos, end_position)
        possibilities.append(end_position-start_pos+1)
    else:
        end_position1 = return_last_position(start_pos, blocks, reverse=True)
        end_position2 = return_last_position(start_pos, blocks, reverse=False)
        print(start_pos, end_position1, end_position1)
        possibilities.append(end_position2-end_position1+1)
        
max(possibilities)


0 1
1 2


2